### ISSUE TITLE
inform your new home

### ISSUE THREAD

**Issue by hugosenari** [MagicRB/NixNG#1]
Hi,
Some friends mentioned it, and this project comes first on search, maybe you could mention in README that, this project moved to nix-community.

**Comment by MagicRB** [comment]
Ive been meaning to archive this repo and do what you suggested for some time, never got to it. Ill do it soon

**Comment by jhillyerd** [comment]
So folks don't have to go searching, https://github.com/nix-community/NixNG

**Comment by hugosenari** [comment]
Would laugh if I told that I found myself now in this same problem, then after some minutes my memory got back to this ticket? :-D

Not so funny feeling: 
> Sad, such nice project 2 years since last commit...

**Comment by hugosenari** [comment]
![image](https://github.com/MagicRB/NixNG/assets/863299/adf5006f-1df8-4fa7-ac44-8bf264c3f53a)

**Comment by MagicRB** [comment]
Yeah sorry, I have the delivery time of, idk insert some company that you hate here. It's done now. See you at the new repo
